// renderer/config/constants.js
// Event types for application-wide usage

export const EventTypes = {
  SVG_SELECTED: 'SVG_SELECTED',
  SVG_DISPLAYED: 'SVG_DISPLAYED',
  SVG_REMOVED: 'SVG_REMOVED',
  SVG_VISIBILITY_CHANGED: 'SVG_VISIBILITY_CHANGED',
  
  COMMAND_LOAD_SVG_FILES: 'COMMAND_LOAD_SVG_FILES',
  COMMAND_SELECT_SVG: 'COMMAND_SELECT_SVG',
  COMMAND_DISPLAY_SVG: 'COMMAND_DISPLAY_SVG'
};
